# Generated by Django 4.2.13 on 2024-06-24 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='nombre',
        ),
    ]
